# <center> Numpy </center>

In [2]:
import numpy as np

# List vs Numpy Array

In [4]:
%timeit [x ** 4 for x in range(1, 10)]

4.73 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.arange(1,10) ** 4

3.93 µs ± 317 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Arrays

In [11]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

# Checking dimension of Array

In [12]:
arr.ndim

1

# Creating 2D Array

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Creating 3D Array

In [18]:
arr = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
arr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

# Creating nD Array

In [20]:
n = 10
arr = np.array([1,2,3,4], ndmin = n)
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

# Indexing

In [7]:
arr = np.array([1,2,3,4,5])
print(arr[3])

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[1, 2])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr
print(arr[1, 0, 2])

4
7
9


# Slicing

In [10]:
arr = np.array([1,2,3,4,5])
print(arr[3:])

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[1, 1:3])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr
print(arr[1, 0, 0:2])

[4 5]
[6 7]
[7 8]


# <center>Data Type </center>

In [13]:
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


## Creating Arrays With a Defined Data Type

In [15]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Converting Data Type on Existing Arrays

In [16]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
#OR newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# <center> NumPy Array Copy vs View </center>

# Copy

In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

#The copy SHOULD NOT be affected by the changes made to the original array.

[42  2  3  4  5]
[1 2 3 4 5]


# View

In [19]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

#The view SHOULD be affected by the changes made to the original array.

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of an Array

In [21]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

#he shape of an array is the number of elements in each dimension.

(2, 4)


# Reshaping arrays
By reshaping we can add or remove dimensions or change number of elements in each dimension.

# Reshape From 1-D to 2-D

In [ ]:
# Convert the following 1-D array with 12 elements into a 2-D array.The outermost dimension
#will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

# Unknown Dimension

In [22]:
# You are allowed to have one "unknown" dimension.
# Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
# Pass -1 as the value, and NumPy will calculate this number for you.


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays

In [23]:
# Flattening array means converting a multidimensional array into a 1D array.

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays

In [28]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


# Iterating Array With Different Data Types

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].



In [30]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


# Iterating With Different Step Size

In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


# Enumerated Iteration Using ndenumerate()

In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
      print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# <center> Special NumPy Arrays </center>

# Array filled with 0's

In [7]:
#1D
arr = np.zeros(4)
print(arr)

#2D (3x4)
arr = np.zeros( (3,4) )
arr

[0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Array filled with 1's

In [12]:
#1D
arr = np.ones(4)
print(arr)

#2D (3x4)
arr = np.ones((3,4))
arr

[1. 1. 1. 1.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Create an empty array

In [14]:
arr = np.empty(4)
arr

# Note : When we create empty array, it takes the previous values from array.

array([1., 1., 1., 1.])

# An array with a range of elements

In [16]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

# Array diagonal elements filled with 1's

In [21]:
arr = np.eye(3)
print(arr)

#3x4 matrix
arr = np.eye(3, 5)
arr

# Note : works on square matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# Arrays with values that are spaced lineraly in a specified interval

In [22]:
arr = np.linspace(0, 10, num = 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])