# <center> Numpy </center>

In [5]:
import numpy as np

In [4]:
%timeit [x ** 4 for x in range(1, 10)]

4.73 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.arange(1,10) ** 4

3.93 µs ± 317 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Arrays

In [11]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

# Checking dimension of Array

In [12]:
arr.ndim

1

# Creating 2D Array

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Creating 3D Array

In [18]:
arr = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
arr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

# Creating nD Array

In [20]:
n = 10
arr = np.array([1,2,3,4], ndmin = n)
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])