# <center> Numpy </center>

In [2]:
import numpy as np

# List vs Numpy Array

In [4]:
%timeit [x ** 4 for x in range(1, 10)]

4.73 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.arange(1,10) ** 4

3.93 µs ± 317 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Arrays

In [11]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

# Checking dimension of Array

In [12]:
arr.ndim

1

# Creating 2D Array

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Creating 3D Array

In [18]:
arr = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
arr

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

# Creating nD Array

In [20]:
n = 10
arr = np.array([1,2,3,4], ndmin = n)
arr

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

# Indexing

In [7]:
arr = np.array([1,2,3,4,5])
print(arr[3])

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[1, 2])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr
print(arr[1, 0, 2])

4
7
9


# Slicing

In [10]:
arr = np.array([1,2,3,4,5])
print(arr[3:])

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[1, 1:3])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr
print(arr[1, 0, 0:2])

[4 5]
[6 7]
[7 8]


# Data Type

In [13]:
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
"""

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


## Creating Arrays With a Defined Data Type

In [15]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## Converting Data Type on Existing Arrays

In [16]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
#OR newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# <center> Special NumPy Arrays </center>

# Array filled with 0's

In [7]:
#1D
arr = np.zeros(4)
print(arr)

#2D (3x4)
arr = np.zeros( (3,4) )
arr

[0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Array filled with 1's

In [12]:
#1D
arr = np.ones(4)
print(arr)

#2D (3x4)
arr = np.ones((3,4))
arr

[1. 1. 1. 1.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Create an empty array

In [14]:
arr = np.empty(4)
arr

# Note : When we create empty array, it takes the previous values from array.

array([1., 1., 1., 1.])

# An array with a range of elements

In [16]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

# Array diagonal elements filled with 1's

In [21]:
arr = np.eye(3)
print(arr)

#3x4 matrix
arr = np.eye(3, 5)
arr

# Note : works on square matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

# Arrays with values that are spaced lineraly in a specified interval

In [22]:
arr = np.linspace(0, 10, num = 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])